account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.RegisterAccountView.as_view(), name='user_register'),
    path('login/', views.LoginAccountView.as_view(), name='user_login'),
    path('logout/', views.LogoutAccountView.as_view(), name='user_logout'),

]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exists')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('this username already exists')
        return username

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password')
        p2 = cd.get('confirm_password')

        if p1 and p2 and p1 != p2:
            raise ValidationError('password must be match')


class UserLoginForm(forms.Form):
    username = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

account/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class RegisterAccountView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'account/register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request, 'success register', 'success')
            return redirect('home:home')
        return render(request, 'account/register.html', {'form': form})

class LoginAccountView(View):
    form_class = UserLoginForm
    template_name = 'account/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username = cd['username'], password = cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'login success', 'success')
                return redirect('home:home')
            messages.error(request, 'username or password is wrong', 'warning')

        return render(request, self.template_name, {'form': form})

class LogoutAccountView(LoginRequiredMixin, View):
    def get(self,request):
        logout(request)
        messages.success(request, 'you logout successfully', 'success')
        return redirect('home:home')
    
    

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
# Create your views here.

class HomeView(View):
    def get(self, request):
        return render(request, 'home/index.html')

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index home</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>social</title>
</head>

<style>
    .jumbotron{
        padding: 20px;
        background-color: #97a7af;
    }

</style>

<body>
    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %}{% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}"> {{ msg }} </p>

    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-dark " data-bs-theme="dark">
  <div class="container-fluid">
      <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          {% if request.user.is_authenticated %}
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_logout' %}">logout</a>
          {% else %}
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_register' %}">register</a>
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_login' %}">login</a>
          {% endif %}
          <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
      </div>
  </div>
</nav>